---
sidebar: sidebar
permalink: task-manage-private-aws.html
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws
summary: Accept a Marketplace private offer for the NetApp Console in the AWS Marketplace Portal and configure AWS credentials in the Console.
---

= Accept and configure an AWS Marketplace private offer for the NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Accept a Marketplace private offer for the NetApp Console in the AWS Marketplace Portal and configure AWS credentials in the Console.

.Before you begin

* Work with NetApp sales to create a private offer and obtain the activation link.  
* Ensure you have the required AWS Marketplace permissions:  
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html[Viewing and subscribing to a private offer]  
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html[Buyer permissions validation]

== Accept the private offer in the AWS Marketplace Portal

Completing the subscription assignment in the Console is required to activate the purchase and apply discounted pricing.  

[NOTE]
You must complete all steps to activate your private offer. Skipping steps may result in billing errors. Accepting and activating the offer multiple times can result in double charging. 

.Steps
. Select the private offer activation link from your NetApp sales team. 
+
The link should look similar to the following: `https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
If you did not receive the link, view private offers in the AWS Marketplace console. The following permissions are required:  
+
* Using AWS managed policies: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions*, or *AWSMarketplaceFullAccess*  
+
* Using custom IAM policies: `aws-marketplace:ListPrivateListings` and `aws-marketplace:ViewSubscriptions`  
. You are redirected to AWS Marketplace to view the private offer.  
+
[NOTE]
Private offers are created on top of public listings. Use the *Offer selection* dropdown to switch between public and private offers.  
+
. Review the private offer details and confirm they match your agreement. If they are incorrect, do not accept. Contact your NetApp account team.  
+
[NOTE]
====
Two types of private offers exist:  

* *On-demand usage*  
** Pricing information  
** Legal terms  

* *Contract*  
** Duration and dates  
** Renewal settings  
** Contract options  
** Total contract price  

For contract offers, enter the number of units agreed upon. For Cloud Volumes ONTAP, ensure you select the correct license before subscribing.  
====

. To accept the private offer, do the following:  
.. For on-demand usage, select *Subscribe*.  
.. For contract offers, enter the number of units for each service and select *Create contract*.  

. After acceptance, a banner confirms the subscription and provides registration instructions.  

. Select *Set up your account*. This redirects to the NetApp Console to configure the subscription.  
+
[NOTE]
====
If you accepted the offer but did not complete registration, return to the product page.  
For contract listings, select *View purchase options* to display the offer, then select *Set up your account*.  
====

. Sign in at https://console.netapp.com.  

. After logging in, navigate to https://console.netapp.com/licenses/overview. You are prompted to:  
.. Enter a *Display name* for the Marketplace subscription.  
.. Select the Console *Organization* with access to the subscription.  
.. [Optional] Enable *Replace existing subscription* to overwrite an existing subscription for an organization.  
+
[NOTE]
====
- Replacement applies only to one Console account.  
- To associate multiple accounts with the same subscription, configure additional accounts manually.  
- If credentials were never associated with a subscription, associate them manually as described in the next section.  
====

. Select **Associate**.
. Complete the form to associate the subscription with your Console organization. Select **Associate**.
. After associating the subscription, select the **Billing preferences** tab.
. Review the marketplace subscription options. 
. Select the marketplace subscription you want to bill. This only applies when there is more than one option. 
. Select **Save changes**.
. Repeat these steps as needed if there are multiple subscriptions across multiple cloud providers. 


For more information on marketplace subscriptions and direct licenses billing, see the link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html[Billing preferences documentation].